/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface AddressDto {
  /** The street address of the user */
  street: string
  /** The city of the user */
  city: string
  /** The ZIP code of the user */
  zipCode: number
}
