/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvertisementByUserIdDto } from './advertisementByUserIdDto'
import type { UserByIdDto } from './userByIdDto'

export interface AdvertisementsByUserDto {
  /** Details of the user */
  user: UserByIdDto
  /** Details of the advertisement */
  advertisement: AdvertisementByUserIdDto
}
