/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Fuel type
 */
export type AdvertisementByUserIdDtoFuel =
  (typeof AdvertisementByUserIdDtoFuel)[keyof typeof AdvertisementByUserIdDtoFuel]

export const AdvertisementByUserIdDtoFuel = {
  Gasoline: 'Gasoline',
  Flex: 'Flex',
  Ethanol: 'Ethanol',
  Diesel: 'Diesel',
  GNV: 'GNV',
  Eletric: 'Eletric',
} as const
