/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Gearbox type
 */
export type AdvertisementByUserIdDtoGearBox =
  (typeof AdvertisementByUserIdDtoGearBox)[keyof typeof AdvertisementByUserIdDtoGearBox]

export const AdvertisementByUserIdDtoGearBox = {
  Automatic: 'Automatic',
  Manual: 'Manual',
} as const
