/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of the advertisement (available, sold, reserved)
 */
export type AdvertisementDtoSoldStatus = (typeof AdvertisementDtoSoldStatus)[keyof typeof AdvertisementDtoSoldStatus]

export const AdvertisementDtoSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
