/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model type
 */
export type AdvertisementByUserIdDtoModel =
  (typeof AdvertisementByUserIdDtoModel)[keyof typeof AdvertisementByUserIdDtoModel]

export const AdvertisementByUserIdDtoModel = {
  SUV: 'SUV',
  Sedan: 'Sedan',
  Hatch: 'Hatch',
  Pickups: 'Pickups',
  Crossover: 'Crossover',
  Stilt: 'Stilt',
  Minivan: 'Minivan',
  Sport: 'Sport',
  Van: 'Van',
  Coupe: 'Coupe',
} as const
