/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Number of doors
 */
export type AdvertisementByUserIdDtoDoors =
  (typeof AdvertisementByUserIdDtoDoors)[keyof typeof AdvertisementByUserIdDtoDoors]

export const AdvertisementByUserIdDtoDoors = {
  Two: 'Two',
  Three: 'Three',
  Four: 'Four',
} as const
