/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Vehicle capacity
 */
export type AdvertisementByUserIdDtoCapacity =
  (typeof AdvertisementByUserIdDtoCapacity)[keyof typeof AdvertisementByUserIdDtoCapacity]

export const AdvertisementByUserIdDtoCapacity = {
  Two: 'Two',
  Four: 'Four',
  Five: 'Five',
  Six: 'Six',
} as const
