/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvertisementDtoSalePrice } from './advertisementDtoSalePrice'
import type { AdvertisementDtoSoldStatus } from './advertisementDtoSoldStatus'

export interface AdvertisementDto {
  /** Creation date of the advertisement */
  createdAt: string
  /** Unique identifier of the advertisement */
  id: string
  /** Price of the advertisement */
  price: number
  /**
   * Sale price of the advertisement
   * @nullable
   */
  salePrice: AdvertisementDtoSalePrice
  /** Status of the advertisement (available, sold, reserved) */
  soldStatus: AdvertisementDtoSoldStatus
  /** Title of the advertisement */
  title: string
}
