/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvertisementByUserIdDtoCapacity } from './advertisementByUserIdDtoCapacity'
import type { AdvertisementByUserIdDtoDoors } from './advertisementByUserIdDtoDoors'
import type { AdvertisementByUserIdDtoFuel } from './advertisementByUserIdDtoFuel'
import type { AdvertisementByUserIdDtoGearBox } from './advertisementByUserIdDtoGearBox'
import type { AdvertisementByUserIdDtoModel } from './advertisementByUserIdDtoModel'
import type { AdvertisementByUserIdDtoSoldStatus } from './advertisementByUserIdDtoSoldStatus'

export interface AdvertisementByUserIdDto {
  /** Creation date of the advertisement */
  createdAt: string
  /** Unique identifier of the advertisement */
  id: string
  /** Title of the advertisement */
  title: string
  /** Price of the advertisement */
  price: number
  /** Sale price of the advertisement */
  salePrice: number
  /** Status of the advertisement (available, sold, reserved) */
  soldStatus: AdvertisementByUserIdDtoSoldStatus
  /** Vehicle mileage */
  km: number
  /** Advertisement thumbnail URL */
  thumbnailUrl: string
  /** BlurHash for the image, used for low-quality image preview */
  blurHash: string
  /** Vehicle capacity */
  capacity: AdvertisementByUserIdDtoCapacity
  /** Number of doors */
  doors: AdvertisementByUserIdDtoDoors
  /** Fuel type */
  fuel: AdvertisementByUserIdDtoFuel
  /** Gearbox type */
  gearBox: AdvertisementByUserIdDtoGearBox
  /** Model type */
  model: AdvertisementByUserIdDtoModel
}
