/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface AvatarDto {
  /** BlurHash representation of the avatar image */
  blurHash: string
  /** URL of the avatar image */
  url: string
  /** Unique identifier of the avatar */
  id: string
}
