/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface BrandDto {
  /** The unique identifier of the brand */
  id: string
  /** The name of the brand */
  name: string
  /** The URL of the brand logo */
  logoUrl: string
}
