/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateFeedbackByAdIdBodyDto {
  /**
   * Feedback comment
   * @maxLength 500
   */
  comment: string
  /** Title of the feedback */
  title: string
  /**
   * Star rating given by the user
   * @minimum 1
   * @maximum 5
   */
  stars: number
}
