/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of fuel used by the vehicle
 */
export type CreateAdBodyDtoFuel = (typeof CreateAdBodyDtoFuel)[keyof typeof CreateAdBodyDtoFuel]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAdBodyDtoFuel = {
  Gasoline: 'Gasoline',
  Flex: 'Flex',
  Ethanol: 'Ethanol',
  Diesel: 'Diesel',
  GNV: 'GNV',
  Eletric: 'Eletric',
} as const
