/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The number of doors of the vehicle
 */
export type CreateAdBodyDtoDoors = (typeof CreateAdBodyDtoDoors)[keyof typeof CreateAdBodyDtoDoors]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAdBodyDtoDoors = {
  Two: 'Two',
  Three: 'Three',
  Four: 'Four',
} as const
