/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The model/type of the vehicle
 */
export type CreateAdBodyDtoModel = (typeof CreateAdBodyDtoModel)[keyof typeof CreateAdBodyDtoModel]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAdBodyDtoModel = {
  SUV: 'SUV',
  Sedan: 'Sedan',
  Hatch: 'Hatch',
  Pickups: 'Pickups',
  Crossover: 'Crossover',
  Stilt: 'Stilt',
  Minivan: 'Minivan',
  Sport: 'Sport',
  Van: 'Van',
  Coupe: 'Coupe',
} as const
