/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAdBodyDtoCapacity } from './createAdBodyDtoCapacity'
import type { CreateAdBodyDtoColor } from './createAdBodyDtoColor'
import type { CreateAdBodyDtoDoors } from './createAdBodyDtoDoors'
import type { CreateAdBodyDtoFuel } from './createAdBodyDtoFuel'
import type { CreateAdBodyDtoGearBox } from './createAdBodyDtoGearBox'
import type { CreateAdBodyDtoModel } from './createAdBodyDtoModel'

export interface CreateAdBodyDto {
  /** The unique identifier of the vehicle brand */
  brandId: string
  /** The seating capacity of the vehicle */
  capacity: CreateAdBodyDtoCapacity
  /** The color of the vehicle */
  color: CreateAdBodyDtoColor
  /** The description of the advertisement */
  description: string
  /** Optional additional details about the vehicle */
  details: string[]
  /** The number of doors of the vehicle */
  doors: CreateAdBodyDtoDoors
  /** The type of fuel used by the vehicle */
  fuel: CreateAdBodyDtoFuel
  /** The type of gearbox in the vehicle */
  gearBox: CreateAdBodyDtoGearBox
  /** The IDs of the advertisement images */
  imagesIds: string[]
  /** The vehicle mileage */
  km: number
  /** The location of the advertisement */
  localization: string
  /** The model/type of the vehicle */
  model: CreateAdBodyDtoModel
  /** The contact phone number */
  phone: string
  /** The price of the vehicle */
  price: number
  /** The thumbnail image ID */
  thumbnailImageId: string
  /** The title of the advertisement */
  title: string
  /** The unique identifier of the user who posted the advertisement */
  userId: string
  /** The year of the vehicle */
  year: number
}
