/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of gearbox in the vehicle
 */
export type CreateAdBodyDtoGearBox = (typeof CreateAdBodyDtoGearBox)[keyof typeof CreateAdBodyDtoGearBox]

export const CreateAdBodyDtoGearBox = {
  Automatic: 'Automatic',
  Manual: 'Manual',
} as const
