/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface FavoritesAdvertisementDto {
  /** Unique identifier of the advertisement */
  id: string
  /** Title of the advertisement */
  title: string
  /** Thumbnail URL of the advertisement */
  thumbnailUrl: string
  /** BlurHash for the image, used for low-quality image preview */
  blurHash: string
  /** Price of the advertisement */
  price: number
  /** Sale price of the advertisement */
  salePrice: number
  /** Kilometers driven */
  km: number
  /** Number of doors */
  doors: string
  /** Gearbox type */
  gearBox: string
  /** Fuel type */
  fuel: string
  /** Vehicle capacity */
  capacity: string
  /** Status of the advertisement */
  soldStatus: string
  /** Model of the advertisement */
  model: string
}
