/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto'

export interface FeedbackDetailsDto {
  /** Unique identifier of the feedback */
  id: string
  /** Title of the feedback */
  title: string
  /** User who provided the feedback */
  user: UserDto
  /** Date when the feedback was created */
  createdAt: string
  /** Star rating given by the user */
  stars: number
  /** User comment */
  comment: string
  /** Total number of likes on this feedback */
  totalLikes: number
}
