/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllUsersParams = {
  /**
   * Page for pagination
   */
  page?: number
  /**
   * Limit for pagination
   */
  limit?: number
}
