/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAdvertisementsMetricsResponseDto } from './findAdvertisementsMetricsResponseDto'

export type FindAdvertisementsMetrics200AllOf = {
  results?: FindAdvertisementsMetricsResponseDto[]
}
