/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface FindAdvertisementsMetricsByUserIdResponseDto {
  /** The number of active advertisements */
  activesAdvertisements: number
  /** The number of reserved advertisements */
  reservedAdvertisements: number
  /** The number of sold advertisements */
  soldAdvertisements: number
  /** The number of total advertisements */
  totalAdvertisements: number
}
