/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllAdvertisementsColor = (typeof FindAllAdvertisementsColor)[keyof typeof FindAllAdvertisementsColor]

export const FindAllAdvertisementsColor = {
  Red: 'Red',
  Black: 'Black',
  Green: 'Green',
  Silver: 'Silver',
  White: 'White',
  Blue: 'Blue',
  Gray: 'Gray',
  Yellow: 'Yellow',
  Orange: 'Orange',
  Metalic: 'Metalic',
  Pink: 'Pink',
  Purple: 'Purple',
  Brown: 'Brown',
} as const
