/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllBrands200AllOf } from './findAllBrands200AllOf'
import type { PaginatedDto } from './paginatedDto'

export type FindAllBrands200 = PaginatedDto & FindAllBrands200AllOf
