/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllAdvertisementsCreatedAt =
  (typeof FindAllAdvertisementsCreatedAt)[keyof typeof FindAllAdvertisementsCreatedAt]

export const FindAllAdvertisementsCreatedAt = {
  asc: 'asc',
  desc: 'desc',
} as const
