/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllFavoritesByUserId200AllOf } from './findAllFavoritesByUserId200AllOf'
import type { PaginatedDto } from './paginatedDto'

export type FindAllFavoritesByUserId200 = PaginatedDto & FindAllFavoritesByUserId200AllOf
