/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface FindAllImagesResponseDto {
  /** Unique identifier of the image */
  id: string
  /** URL of the uploaded image */
  url: string
  /** Creation date of the image */
  createdAt: string
  /** Last update date of the image */
  updatedAt: string
}
