/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvertisementDto } from './advertisementDto'
import type { UserDto } from './userDto'

export interface FindAllFavoritesResponseDto {
  /** Details of the advertisement related to the favorite */
  advertisement: AdvertisementDto
  /** Date when the favorite was created */
  createdAt: string
  /** Count of users who have favorited this advertisement */
  favoritesCount: number
  /** Unique identifier of the favorite details */
  id: string
  /** Details of the user who favorited the advertisement */
  user: UserDto
}
