/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllUsersCreatedAt = (typeof FindAllUsersCreatedAt)[keyof typeof FindAllUsersCreatedAt]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAllUsersCreatedAt = {
  asc: 'asc',
  desc: 'desc',
} as const
