/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of fuel of the vehicle
 */
export type FindAdByIdResponseDtoFuel = (typeof FindAdByIdResponseDtoFuel)[keyof typeof FindAdByIdResponseDtoFuel]

export const FindAdByIdResponseDtoFuel = {
  Gasoline: 'Gasoline',
  Flex: 'Flex',
  Ethanol: 'Ethanol',
  Diesel: 'Diesel',
  GNV: 'GNV',
  Eletric: 'Eletric',
} as const
