/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedDto } from './paginatedDto'
import type { FindAllUsers200AllOf } from './findAllUsers200AllOf'

export type FindAllUsers200 = PaginatedDto & FindAllUsers200AllOf
