/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllUsersName = (typeof FindAllUsersName)[keyof typeof FindAllUsersName]

export const FindAllUsersName = {
  asc: 'asc',
  desc: 'desc',
} as const
