/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { OwnAdvertisementsDto } from './ownAdvertisementsDto'

export type FindAllOwnAdvertisements200AllOf = {
  results?: OwnAdvertisementsDto[]
}
