/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllSoldAds200AllOf } from './findAllSoldAds200AllOf'
import type { PaginatedDto } from './paginatedDto'

export type FindAllSoldAds200 = PaginatedDto & FindAllSoldAds200AllOf
