/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllImagesResponseDto } from './findAllImagesResponseDto'

export type FindAllImages200AllOf = {
  results?: FindAllImagesResponseDto[]
}
