/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllUsersStatus = (typeof FindAllUsersStatus)[keyof typeof FindAllUsersStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAllUsersStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const
