/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllManagerAdvertisementsCreatedAt =
  (typeof FindAllManagerAdvertisementsCreatedAt)[keyof typeof FindAllManagerAdvertisementsCreatedAt]

export const FindAllManagerAdvertisementsCreatedAt = {
  asc: 'asc',
  desc: 'desc',
} as const
