/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of gearbox in the vehicle
 */
export type FindAdByIdResponseDtoGearBox =
  (typeof FindAdByIdResponseDtoGearBox)[keyof typeof FindAdByIdResponseDtoGearBox]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAdByIdResponseDtoGearBox = {
  Automatic: 'Automatic',
  Manual: 'Manual',
} as const
