/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FavoritesAdvertisementDto } from './favoritesAdvertisementDto'

export interface FindAllFavoritesByUserIdResponseDto {
  /** Unique identifier of the favorites */
  id: string
  /** Details of the advertisement related to the favorite */
  advertisement: FavoritesAdvertisementDto
}
