/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllUsers } from './findAllUsers'

export type FindAllUsers200AllOf = {
  results?: FindAllUsers[]
}
