/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllManagerAdvertisementsSoldStatus =
  (typeof FindAllManagerAdvertisementsSoldStatus)[keyof typeof FindAllManagerAdvertisementsSoldStatus]

export const FindAllManagerAdvertisementsSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
