/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The color of the vehicle
 */
export type FindAdByIdResponseDtoColor = (typeof FindAdByIdResponseDtoColor)[keyof typeof FindAdByIdResponseDtoColor]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAdByIdResponseDtoColor = {
  Red: 'Red',
  Black: 'Black',
  Green: 'Green',
  Silver: 'Silver',
  White: 'White',
  Blue: 'Blue',
  Gray: 'Gray',
  Yellow: 'Yellow',
  Orange: 'Orange',
  Metalic: 'Metalic',
  Pink: 'Pink',
  Purple: 'Purple',
} as const
