/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedDto } from './paginatedDto'
import type { FindAllOwnAdvertisements200AllOf } from './findAllOwnAdvertisements200AllOf'

export type FindAllOwnAdvertisements200 = PaginatedDto & FindAllOwnAdvertisements200AllOf
