/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllAdvertisementsParams = {
  /**
   * The model/type of the vehicle
   */
  model: unknown
  /**
   * The type of fuel of the vehicle
   */
  fuel: unknown
  /**
   * The maximum desired mileage
   */
  km: number
  /**
   * The brand of the vehicle
   */
  brand: string
  /**
   * The color of the vehicle
   */
  color: unknown
  /**
   * The year of the vehicle
   */
  year: number
  /**
   * The maximum desired price
   */
  price: number
  /**
   * The order of advertisements by date
   */
  date: unknown
  /**
   * The order of advertisements by likes
   */
  likes: unknown
  /**
   * Page number to send to API
   */
  page?: string
  /**
   * Limit of data to be returned from the API
   */
  limit?: string
  /**
   * Page for pagination
   */
  page?: number
  /**
   * Limit for pagination
   */
  limit?: number
}
