/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllAdvertisementsByUserId200AllOf } from './findAllAdvertisementsByUserId200AllOf'
import type { PaginatedDto } from './paginatedDto'

export type FindAllAdvertisementsByUserId200 = PaginatedDto & FindAllAdvertisementsByUserId200AllOf
