/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedDto } from './paginatedDto'
import type { FindAllImages200AllOf } from './findAllImages200AllOf'

export type FindAllImages200 = PaginatedDto & FindAllImages200AllOf
