/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { FindAdvertisementsMetricsByUserId200AllOf } from './findAdvertisementsMetricsByUserId200AllOf'
import type { PaginatedDto } from './paginatedDto'

export type FindAdvertisementsMetricsByUserId200 = PaginatedDto & FindAdvertisementsMetricsByUserId200AllOf
