/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedDto } from './paginatedDto'
import type { FindAllManagerAdvertisements200AllOf } from './findAllManagerAdvertisements200AllOf'

export type FindAllManagerAdvertisements200 = PaginatedDto & FindAllManagerAdvertisements200AllOf
