/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllOwnAdvertisementsSoldStatus =
  (typeof FindAllOwnAdvertisementsSoldStatus)[keyof typeof FindAllOwnAdvertisementsSoldStatus]

export const FindAllOwnAdvertisementsSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
