/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { BrandDto } from './brandDto'
import type { FindAdByIdResponseDtoCapacity } from './findAdByIdResponseDtoCapacity'
import type { FindAdByIdResponseDtoColor } from './findAdByIdResponseDtoColor'
import type { FindAdByIdResponseDtoDoors } from './findAdByIdResponseDtoDoors'
import type { FindAdByIdResponseDtoFuel } from './findAdByIdResponseDtoFuel'
import type { FindAdByIdResponseDtoGearBox } from './findAdByIdResponseDtoGearBox'
import type { FindAdByIdResponseDtoModel } from './findAdByIdResponseDtoModel'
import type { FindAdByIdResponseDtoSoldStatus } from './findAdByIdResponseDtoSoldStatus'
import type { ImageDto } from './imageDto'
import type { UserDto } from './userDto'

export interface FindAdByIdResponseDto {
  /** Details about the vehicle brand */
  brand: BrandDto
  /** The seating capacity of the vehicle */
  capacity: FindAdByIdResponseDtoCapacity
  /** The color of the vehicle */
  color: FindAdByIdResponseDtoColor
  /** The creation date of the advertisement */
  createdAt: string
  /** The description of the advertisement */
  description: string
  /** Optional additional details about the vehicle */
  details: string[]
  /** The number of doors of the vehicle */
  doors: FindAdByIdResponseDtoDoors
  /** The type of fuel of the vehicle */
  fuel: FindAdByIdResponseDtoFuel
  /** The type of gearbox in the vehicle */
  gearBox: FindAdByIdResponseDtoGearBox
  /** Array of image URLs */
  images: ImageDto[]
  /** The mileage of the vehicle */
  km: number
  /** The location of the advertisement */
  localization: string
  /** The model/type of the vehicle */
  model: FindAdByIdResponseDtoModel
  /** The contact phone number */
  phone: string
  /** The price of the vehicle */
  price: number
  /** The sale price of the vehicle (if applicable) */
  salePrice: number
  /** The sold status of the vehicle */
  soldStatus: FindAdByIdResponseDtoSoldStatus
  /** The title of the advertisement */
  title: string
  /** The last update date of the advertisement (if applicable) */
  updatedAt: string
  /** Details about the user who created the advertisement */
  user: UserDto
  /** The year of the vehicle */
  year: number
}
