/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export type FindAllUsersRole = (typeof FindAllUsersRole)[keyof typeof FindAllUsersRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAllUsersRole = {
  Manager: 'Manager',
  Seller: 'Seller',
  Customer: 'Customer',
} as const
