/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The seating capacity of the vehicle
 */
export type FindAdByIdResponseDtoCapacity =
  (typeof FindAdByIdResponseDtoCapacity)[keyof typeof FindAdByIdResponseDtoCapacity]

export const FindAdByIdResponseDtoCapacity = {
  Two: 'Two',
  Four: 'Four',
  Five: 'Five',
  Six: 'Six',
} as const
