/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface ImageDto {
  /** The URL of the image */
  url: string
  /** BlurHash for the image, used for low-quality image preview */
  blurHash: string
  /** The unique identifier of the image */
  id: string
  /** The identifier if image is thumbnail */
  isThumbnail: string
}
