/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of the advertisement (available, sold, reserved)
 */
export type ManagerAdvertisementsDtoSoldStatus =
  (typeof ManagerAdvertisementsDtoSoldStatus)[keyof typeof ManagerAdvertisementsDtoSoldStatus]

export const ManagerAdvertisementsDtoSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
