/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface MeAddressDto {
  /** Address ID */
  id: string
  /** Street name */
  street: string
  /** City name */
  city: string
  /** State code */
  state: string
  /** Postal code (ZIP) */
  zipCode: number
  /** Country */
  country: string
  /** Neighborhood name */
  neighborhood: string
}
