/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { MeUserDto } from './meUserDto'
import type { MeAddressDto } from './meAddressDto'

export interface MeDto {
  /** Informações do usuário */
  user: MeUserDto
  /** Endereço do usuário */
  address: MeAddressDto
}
