/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface MetaDto {
  /** Page index */
  page: number
  /** Total itens per page */
  perPage: number
  /** Total itens found in database */
  totalCount: number
  /** Total pages found in database */
  totalPages: number
}
