/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface MeUserDto {
  /** User ID */
  id: string
  /** User roles */
  roles: string[]
  /** User name */
  name: string
  /** User image BlurHash */
  blurHash?: string
  /** User avatar URL */
  avatar?: string
  /** User email */
  email: string
  /** User username */
  username: string
}
