/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { LikeEntity } from './likeEntity'
import type { MinimalAdvertisementDetailsDtoCapacity } from './minimalAdvertisementDetailsDtoCapacity'
import type { MinimalAdvertisementDetailsDtoDoors } from './minimalAdvertisementDetailsDtoDoors'
import type { MinimalAdvertisementDetailsDtoFuel } from './minimalAdvertisementDetailsDtoFuel'
import type { MinimalAdvertisementDetailsDtoGearBox } from './minimalAdvertisementDetailsDtoGearBox'

export interface MinimalAdvertisementDetailsDto {
  /** URL da imagem da marca */
  logoUrl: string
  /** Nome da marca */
  name: string
  /** ID único da marca */
  brandId: string
  /** Kilometragem do veículo */
  km: number
  /** Preço do veículo */
  price: number
  /** Título do anúncio */
  title: string
  /** ID único do anúncio */
  advertisementId: string
  /** URL da miniatura do anúncio */
  thumbnailUrl: string
  /** BlurHash for the image, used for low-quality image preview */
  blurHash: string
  /** Capacidade do veículo */
  capacity: MinimalAdvertisementDetailsDtoCapacity
  /** Número de portas do veículo */
  doors: MinimalAdvertisementDetailsDtoDoors
  /** Tipo de combustível */
  fuel: MinimalAdvertisementDetailsDtoFuel
  /** Tipo de câmbio */
  gearBox: MinimalAdvertisementDetailsDtoGearBox
  /** Curtidas no anúncio */
  likes?: LikeEntity[]
}
