/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Vehicle capacity
 */
export type MinimalAdvertisementDetailsDtoCapacity =
  (typeof MinimalAdvertisementDetailsDtoCapacity)[keyof typeof MinimalAdvertisementDetailsDtoCapacity]

export const MinimalAdvertisementDetailsDtoCapacity = {
  Two: 'Two',
  Four: 'Four',
  Five: 'Five',
  Six: 'Six',
} as const
