/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { LikeEntity } from './likeEntity'
import type { MinimalAdvertisementDetailsDtoCapacity } from './minimalAdvertisementDetailsDtoCapacity'
import type { MinimalAdvertisementDetailsDtoDoors } from './minimalAdvertisementDetailsDtoDoors'
import type { MinimalAdvertisementDetailsDtoFuel } from './minimalAdvertisementDetailsDtoFuel'
import type { MinimalAdvertisementDetailsDtoGearBox } from './minimalAdvertisementDetailsDtoGearBox'

export interface MinimalAdvertisementDetailsDto {
  /** ID único do anúncio */
  advertisementId: string
  /** ID único da marca */
  brandId: string
  /** Capacidade do veículo */
  capacity: MinimalAdvertisementDetailsDtoCapacity
  /** Número de portas do veículo */
  doors: MinimalAdvertisementDetailsDtoDoors
  /** Tipo de combustível */
  fuel: MinimalAdvertisementDetailsDtoFuel
  /** Tipo de câmbio */
  gearBox: MinimalAdvertisementDetailsDtoGearBox
  /** URL da imagem da marca */
  imageUrl: string
  /** Kilometragem do veículo */
  km: number
  /** Curtidas no anúncio */
  likes?: LikeEntity[]
  /** Nome da marca */
  name: string
  /** Preço do veículo */
  price: number
  /** URL da miniatura do anúncio */
  thumbnailUrl: string
  /** Título do anúncio */
  title: string
}
