/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Número de portas do veículo
 */
export type MinimalAdvertisementDetailsDtoDoors =
  (typeof MinimalAdvertisementDetailsDtoDoors)[keyof typeof MinimalAdvertisementDetailsDtoDoors]

export const MinimalAdvertisementDetailsDtoDoors = {
  Two: 'Two',
  Three: 'Three',
  Four: 'Four',
} as const
