/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Gearbox type
 */
export type MinimalAdvertisementDetailsDtoGearBox =
  (typeof MinimalAdvertisementDetailsDtoGearBox)[keyof typeof MinimalAdvertisementDetailsDtoGearBox]

export const MinimalAdvertisementDetailsDtoGearBox = {
  Automatic: 'Automatic',
  Manual: 'Manual',
} as const
