/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model type
 */
export type MinimalAdvertisementDetailsDtoModel =
  (typeof MinimalAdvertisementDetailsDtoModel)[keyof typeof MinimalAdvertisementDetailsDtoModel]

export const MinimalAdvertisementDetailsDtoModel = {
  SUV: 'SUV',
  Sedan: 'Sedan',
  Hatch: 'Hatch',
  Pickups: 'Pickups',
  Crossover: 'Crossover',
  Stilt: 'Stilt',
  Minivan: 'Minivan',
  Sport: 'Sport',
  Van: 'Van',
  Coupe: 'Coupe',
} as const
