/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of advertisement
 */
export type MinimalAdvertisementDetailsDtoSoldStatus =
  (typeof MinimalAdvertisementDetailsDtoSoldStatus)[keyof typeof MinimalAdvertisementDetailsDtoSoldStatus]

export const MinimalAdvertisementDetailsDtoSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
