/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface OwnAdvertisementBrandDto {
  /** Name of the brand */
  name: string
  /** Logo URL of the brand */
  logoUrl: string
  /** Unique identifier of the brand */
  id: string
}
