/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of the advertisement (available, sold, reserved)
 */
export type OwnAdvertisementsDtoSoldStatus =
  (typeof OwnAdvertisementsDtoSoldStatus)[keyof typeof OwnAdvertisementsDtoSoldStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OwnAdvertisementsDtoSoldStatus = {
  Sold: 'Sold',
  Active: 'Active',
  Reserved: 'Reserved',
} as const
