/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpBodyDto {
  /** The city of the address */
  city: string
  /** The country of the address */
  country: string
  /** The user email */
  email: string
  /** The user's full name */
  name: string
  /** The neighborhood of the address */
  neighborhood: string
  /** The user password */
  password: string
  /** The user's role */
  role: string
  /** The state of the address */
  state: string
  /** The street of the address */
  street: string
  /** The username */
  username: string
  /** The zip code of the address */
  zipCode: number
}
