/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateOwnUserBodyDto {
  /** The URL for the user avatar */
  avatar?: string
  /** The user's full name */
  name?: string
  /** The username */
  username?: string
  /** The user's role */
  role?: string
}
