/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdDTOCapacity } from './updateAdDTOCapacity'
import type { UpdateAdDTOColor } from './updateAdDTOColor'
import type { UpdateAdDTODoors } from './updateAdDTODoors'
import type { UpdateAdDTOFuel } from './updateAdDTOFuel'
import type { UpdateAdDTOGearBox } from './updateAdDTOGearBox'
import type { UpdateAdDTOModel } from './updateAdDTOModel'
import type { UpdateAdDTOSoldStatus } from './updateAdDTOSoldStatus'

export interface UpdateAdDTO {
  /** The unique identifier of the vehicle’s brand */
  brandId?: string
  /** The seating capacity of the vehicle */
  capacity?: UpdateAdDTOCapacity
  /** The color of the vehicle */
  color?: UpdateAdDTOColor
  /** The advertisement description */
  description?: string
  /** Additional optional details about the vehicle */
  details?: string[]
  /** Number of doors of the vehicle */
  doors?: UpdateAdDTODoors
  /** The type of fuel the vehicle uses */
  fuel?: UpdateAdDTOFuel
  /** The type of gear transmission in the vehicle */
  gearBox?: UpdateAdDTOGearBox
  /** The vehicle’s mileage */
  km?: number
  /** The location of the advertisement */
  localization?: string
  /** The model/type of the vehicle */
  model?: UpdateAdDTOModel
  /** The contact phone number */
  phone?: string
  /** The price of the vehicle */
  price?: number
  /** The sale price of the vehicle if it was sold */
  salePrice?: number
  /** Flag indicating if the vehicle has been sold */
  soldStatus?: UpdateAdDTOSoldStatus
  /** The ID of thumbnail image */
  thumbnailImageId?: string
  /** The title of the advertisement */
  title?: string
  /** The vehicle’s year */
  year?: number
}
