/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of fuel the vehicle uses
 */
export type UpdateAdDTOFuel = (typeof UpdateAdDTOFuel)[keyof typeof UpdateAdDTOFuel]

export const UpdateAdDTOFuel = {
  Gasoline: 'Gasoline',
  Flex: 'Flex',
  Ethanol: 'Ethanol',
  Diesel: 'Diesel',
  GNV: 'GNV',
  Eletric: 'Eletric',
} as const
