/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AddressDto } from './addressDto'

export interface UserDto {
  /** The address of the user */
  address: AddressDto
  /** The unique identifier of the user */
  id: string
  /** The name of the user */
  name: string
}
