/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvertisementDto } from './advertisementDto'
import type { UserDto } from './userDto'

export interface UserAdvertisementsPropsDto {
  /** Details of the user */
  user: UserDto
  /** Details of the advertisement */
  advertisement: AdvertisementDto
}
