/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */

export interface UserByIdDto {
  /** URL of the user profile image */
  profileImg: string
  /** Username of the user */
  username: string
  /** Unique identifier of the user */
  id: string
}
