/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Auto Cars - Backend
 * Cars seller API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker'
import { HttpResponse, delay, http } from 'msw'

import type { UpdateAddressResponseDto } from '../../schemas'

export const getUpdateAddressResponseMock = (
  overrideResponse: Partial<UpdateAddressResponseDto> = {},
): UpdateAddressResponseDto => ({ message: faker.string.alpha(20), ...overrideResponse })

export const getUpdateAddressMockHandler = (
  overrideResponse?:
    | UpdateAddressResponseDto
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<UpdateAddressResponseDto> | UpdateAddressResponseDto),
) => {
  return http.patch('*/address', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateAddressResponseMock(),
      ),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getAddressControllerMock = () => [getUpdateAddressMockHandler()]
